export const PLAYLISTS_REQUEST = "PLAYLISTS_REQUEST";
export const PLAYLISTS_SUCCESS = "PLAYLISTS_SUCCESS";
export const PLAYLISTS_FAIL = "PLAYLISTS_FAIL";

export const PLAYLIST_REQUEST = "PLAYLIST_REQUEST";
export const PLAYLIST_SUCCESS = "PLAYLIST_SUCCESS";
export const PLAYLIST_FAIL = "PLAYLIST_FAIL";

export const PLAYLIST_ADD_REQUEST = "PLAYLIST_ADD_REQUEST";
export const PLAYLIST_ADD_SUCCESS = "PLAYLIST_ADD_SUCCESS";
export const PLAYLIST_ADD_FAIL = "PLAYLIST_ADD_FAIL";
export const PLAYLIST_ADD_RESET = "PLAYLIST_ADD_RESET";

export const PLAYLIST_REMOVE_REQUEST = "PLAYLIST_REMOVE_REQUEST";
export const PLAYLIST_REMOVE_SUCCESS = "PLAYLIST_REMOVE_SUCCESS";
export const PLAYLIST_REMOVE_FAIL = "PLAYLIST_REMOVE_FAIL";
export const PLAYLIST_REMOVE_RESET = "PLAYLIST_REMOVE_RESET";

export const PLAYLIST_EDIT_REQUEST = "PLAYLIST_EDIT_REQUEST";
export const PLAYLIST_EDIT_SUCCESS = "PLAYLIST_EDIT_SUCCESS";
export const PLAYLIST_EDIT_FAIL = "PLAYLIST_EDIT_FAIL";
export const PLAYLIST_EDIT_RESET = "PLAYLIST_EDIT_RESET";
