export const PLAYLISTS_REQUEST = "PLAYLISTS_REQUEST";
export const PLAYLISTS_SUCCESS = "PLAYLISTS_SUCCESS";
export const PLAYLISTS_FAIL = "PLAYLISTS_FAIL";

export const PLAYLIST_REQUEST = "PLAYLIST_REQUEST";
export const PLAYLIST_SUCCESS = "PLAYLIST_SUCCESS";
export const PLAYLIST_FAIL = "PLAYLIST_FAIL";

export const PLAYLIST_ADD_REQUEST = "PLAYLIST_ADD_REQUEST";
export const PLAYLIST_ADD_SUCCESS = "PLAYLIST_ADD_SUCCESS";
export const PLAYLIST_ADD_FAIL = "PLAYLIST_ADD_FAIL";
export const PLAYLIST_ADD_RESET = "PLAYLIST_ADD_RESET";
