export const SONG_REMOVE_REQUEST = "SONG_REMOVE_REQUEST";
export const SONG_REMOVE_SUCCESS = "SONG_REMOVE_SUCCESS";
export const SONG_REMOVE_FAIL = "SONG_REMOVE_FAIL";
export const SONG_REMOVE_RESET = "SONG_REMOVE_RESET";
