export const SONG_REMOVE_REQUEST = "SONG_REMOVE_REQUEST";
export const SONG_REMOVE_SUCCESS = "SONG_REMOVE_SUCCESS";
export const SONG_REMOVE_FAIL = "SONG_REMOVE_FAIL";
export const SONG_REMOVE_RESET = "SONG_REMOVE_RESET";

export const SONG_ADD_REQUEST = "SONG_ADD_REQUEST";
export const SONG_ADD_SUCCESS = "SONG_ADD_SUCCESS";
export const SONG_ADD_FAIL = "SONG_ADD_FAIL";
export const SONG_ADD_RESET = "SONG_ADD_RESET";

export const SONGS_REQUEST = "SONGS_REQUEST";
export const SONGS_SUCCESS = "SONGS_SUCCESS";
export const SONGS_FAIL = "SONGS_FAIL";

export const SONG_REQUEST = "SONG_REQUEST";
export const SONG_SUCCESS = "SONG_SUCCESS";
export const SONG_FAIL = "SONG_FAIL";

export const SONG_CURRENT_REQUEST = "SONG_CURRENT_REQUEST";
export const SONG_CURRENT_SUCCESS = "SONG_CURRENT_SUCCESS";
export const SONG_CURRENT_FAIL = "SONG_CURRENT_FAIL";
